// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler

import (
	domain "github.com/mishasvintus/avito_backend_internship/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockPRServiceInterface is an autogenerated mock type for the PRServiceInterface type
type MockPRServiceInterface struct {
	mock.Mock
}

type MockPRServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRServiceInterface) EXPECT() *MockPRServiceInterface_Expecter {
	return &MockPRServiceInterface_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function with given fields: prID, prName, authorID
func (_m *MockPRServiceInterface) CreatePR(prID string, prName string, authorID string) (*domain.PullRequest, error) {
	ret := _m.Called(prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.PullRequest, error)); ok {
		return rf(prID, prName, authorID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.PullRequest); ok {
		r0 = rf(prID, prName, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(prID, prName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRServiceInterface_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockPRServiceInterface_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - prID string
//   - prName string
//   - authorID string
func (_e *MockPRServiceInterface_Expecter) CreatePR(prID interface{}, prName interface{}, authorID interface{}) *MockPRServiceInterface_CreatePR_Call {
	return &MockPRServiceInterface_CreatePR_Call{Call: _e.mock.On("CreatePR", prID, prName, authorID)}
}

func (_c *MockPRServiceInterface_CreatePR_Call) Run(run func(prID string, prName string, authorID string)) *MockPRServiceInterface_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPRServiceInterface_CreatePR_Call) Return(_a0 *domain.PullRequest, _a1 error) *MockPRServiceInterface_CreatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRServiceInterface_CreatePR_Call) RunAndReturn(run func(string, string, string) (*domain.PullRequest, error)) *MockPRServiceInterface_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: prID
func (_m *MockPRServiceInterface) MergePR(prID string) (*domain.PullRequest, error) {
	ret := _m.Called(prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.PullRequest, error)); ok {
		return rf(prID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.PullRequest); ok {
		r0 = rf(prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRServiceInterface_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type MockPRServiceInterface_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - prID string
func (_e *MockPRServiceInterface_Expecter) MergePR(prID interface{}) *MockPRServiceInterface_MergePR_Call {
	return &MockPRServiceInterface_MergePR_Call{Call: _e.mock.On("MergePR", prID)}
}

func (_c *MockPRServiceInterface_MergePR_Call) Run(run func(prID string)) *MockPRServiceInterface_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPRServiceInterface_MergePR_Call) Return(_a0 *domain.PullRequest, _a1 error) *MockPRServiceInterface_MergePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRServiceInterface_MergePR_Call) RunAndReturn(run func(string) (*domain.PullRequest, error)) *MockPRServiceInterface_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignPR provides a mock function with given fields: prID, oldReviewerID
func (_m *MockPRServiceInterface) ReassignPR(prID string, oldReviewerID string) (*domain.PullRequest, string, error) {
	ret := _m.Called(prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignPR")
	}

	var r0 *domain.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.PullRequest, string, error)); ok {
		return rf(prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.PullRequest); ok {
		r0 = rf(prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(prID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPRServiceInterface_ReassignPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignPR'
type MockPRServiceInterface_ReassignPR_Call struct {
	*mock.Call
}

// ReassignPR is a helper method to define mock.On call
//   - prID string
//   - oldReviewerID string
func (_e *MockPRServiceInterface_Expecter) ReassignPR(prID interface{}, oldReviewerID interface{}) *MockPRServiceInterface_ReassignPR_Call {
	return &MockPRServiceInterface_ReassignPR_Call{Call: _e.mock.On("ReassignPR", prID, oldReviewerID)}
}

func (_c *MockPRServiceInterface_ReassignPR_Call) Run(run func(prID string, oldReviewerID string)) *MockPRServiceInterface_ReassignPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPRServiceInterface_ReassignPR_Call) Return(_a0 *domain.PullRequest, _a1 string, _a2 error) *MockPRServiceInterface_ReassignPR_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPRServiceInterface_ReassignPR_Call) RunAndReturn(run func(string, string) (*domain.PullRequest, string, error)) *MockPRServiceInterface_ReassignPR_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPRServiceInterface creates a new instance of MockPRServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRServiceInterface {
	mock := &MockPRServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
