// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/mishasvintus/avito_backend_internship/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// GetUserReviews provides a mock function with given fields: userID
func (_m *MockUserServiceInterface) GetUserReviews(userID string) ([]domain.PullRequestShort, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviews")
	}

	var r0 []domain.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.PullRequestShort, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.PullRequestShort); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_GetUserReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReviews'
type MockUserServiceInterface_GetUserReviews_Call struct {
	*mock.Call
}

// GetUserReviews is a helper method to define mock.On call
//   - userID string
func (_e *MockUserServiceInterface_Expecter) GetUserReviews(userID interface{}) *MockUserServiceInterface_GetUserReviews_Call {
	return &MockUserServiceInterface_GetUserReviews_Call{Call: _e.mock.On("GetUserReviews", userID)}
}

func (_c *MockUserServiceInterface_GetUserReviews_Call) Run(run func(userID string)) *MockUserServiceInterface_GetUserReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetUserReviews_Call) Return(_a0 []domain.PullRequestShort, _a1 error) *MockUserServiceInterface_GetUserReviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_GetUserReviews_Call) RunAndReturn(run func(string) ([]domain.PullRequestShort, error)) *MockUserServiceInterface_GetUserReviews_Call {
	_c.Call.Return(run)
	return _c
}

// SetIsActive provides a mock function with given fields: userID, isActive
func (_m *MockUserServiceInterface) SetIsActive(userID string, isActive bool) (*domain.User, error) {
	ret := _m.Called(userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*domain.User, error)); ok {
		return rf(userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *domain.User); ok {
		r0 = rf(userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_SetIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsActive'
type MockUserServiceInterface_SetIsActive_Call struct {
	*mock.Call
}

// SetIsActive is a helper method to define mock.On call
//   - userID string
//   - isActive bool
func (_e *MockUserServiceInterface_Expecter) SetIsActive(userID interface{}, isActive interface{}) *MockUserServiceInterface_SetIsActive_Call {
	return &MockUserServiceInterface_SetIsActive_Call{Call: _e.mock.On("SetIsActive", userID, isActive)}
}

func (_c *MockUserServiceInterface_SetIsActive_Call) Run(run func(userID string, isActive bool)) *MockUserServiceInterface_SetIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockUserServiceInterface_SetIsActive_Call) Return(_a0 *domain.User, _a1 error) *MockUserServiceInterface_SetIsActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_SetIsActive_Call) RunAndReturn(run func(string, bool) (*domain.User, error)) *MockUserServiceInterface_SetIsActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
