// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	service "github.com/mishasvintus/avito_backend_internship/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// MockStatsServiceInterface is an autogenerated mock type for the StatsServiceInterface type
type MockStatsServiceInterface struct {
	mock.Mock
}

type MockStatsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsServiceInterface) EXPECT() *MockStatsServiceInterface_Expecter {
	return &MockStatsServiceInterface_Expecter{mock: &_m.Mock}
}

// GetStatistics provides a mock function with no fields
func (_m *MockStatsServiceInterface) GetStatistics() (*service.Statistics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 *service.Statistics
	var r1 error
	if rf, ok := ret.Get(0).(func() (*service.Statistics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *service.Statistics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Statistics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServiceInterface_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockStatsServiceInterface_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
func (_e *MockStatsServiceInterface_Expecter) GetStatistics() *MockStatsServiceInterface_GetStatistics_Call {
	return &MockStatsServiceInterface_GetStatistics_Call{Call: _e.mock.On("GetStatistics")}
}

func (_c *MockStatsServiceInterface_GetStatistics_Call) Run(run func()) *MockStatsServiceInterface_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsServiceInterface_GetStatistics_Call) Return(_a0 *service.Statistics, _a1 error) *MockStatsServiceInterface_GetStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServiceInterface_GetStatistics_Call) RunAndReturn(run func() (*service.Statistics, error)) *MockStatsServiceInterface_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsServiceInterface creates a new instance of MockStatsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsServiceInterface {
	mock := &MockStatsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
