with-expecter: true
packages:
  github.com/mishasvintus/avito_backend_internship/internal/handler:
    interfaces:
      TeamServiceInterface:
        config:
          dir: "tests/mocks"
          filename: "mock_team_service.go"
          mockname: "MockTeamServiceInterface"
          packagename: "mocks"
      UserServiceInterface:
        config:
          dir: "tests/mocks"
          filename: "mock_user_service.go"
          mockname: "MockUserServiceInterface"
          packagename: "mocks"
      PRServiceInterface:
        config:
          dir: "tests/mocks"
          filename: "mock_pr_service.go"
          mockname: "MockPRServiceInterface"
          packagename: "mocks"

