with-expecter: true
outpkg: mocks
dir: "tests/mocks"
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/mishasvintus/avito_backend_internship/internal/handler:
    interfaces:
      TeamServiceInterface:
      UserServiceInterface:
      PRServiceInterface:
      StatsServiceInterface:

